controller_manager:
  ros__parameters:
    # Match the default Axia sample_rate_code=0 exact rate from the ATI manual.
    update_rate: 487

    ati_axia80_m20_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

ati_axia80_m20_broadcaster:
  ros__parameters:
    sensor_name: ati_axia80_m20
    frame_id: ati_axia80_m20_link
